Adding sharedid submodule
SKOCHERI/Prebid.js pull request #1
Opened 2020-04-10 17:02 UTC by SKOCHERI

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2020-04-14 13:47 UTC, brodrigu requested changes

2020-04-14 13:47 UTC, brodrigu commented on integrationExamples/gpt/userId_example.html
> +                        name: "sharedId",
```suggestion
                        name: "sharedid",
```
it looks like storage.name is lowercase in all other examples, we should probably keep that consistency.

2020-04-14 13:47 UTC, brodrigu commented on modules/sharedIdSystem.js
> +   * @returns {{sharedId:string}}
this could also return `undefined`. if intentional, we should indicate here.

2020-04-14 13:47 UTC, brodrigu commented on modules/sharedIdSystem.js
> +      id: sharedId }
```suggestion
      id: sharedId
    }
```

2020-04-14 13:47 UTC, brodrigu commented on modules/sharedIdSystem.js
> +  sharedIdGenerator: function () {
ideally, we should add docBlocks for all functions.

2020-04-14 13:47 UTC, brodrigu commented on modules/sharedIdSystem.js
> +  factory: function (currPrng) {
I had to google what `Prng` stands for, would be good to indicate what that is here. A docBlock would solve for this.

2020-04-14 13:47 UTC, brodrigu commented on modules/sharedIdSystem.js
> +    };
in `sharedIdGenerator` we pull out `sharedIdFactory` to its own, independent, class method. Here we are defining `ulid` inline. Is this necessary? if not, I might suggest pulling it into a separate method and reference it here instead.

2020-04-14 13:47 UTC, brodrigu commented on modules/sharedIdSystem.js
> +    if (Number.isInteger(now) === false) {
you should check this condition before comparing to `0` or `TIME_MAX`

2020-04-14 13:47 UTC, brodrigu commented on modules/sharedIdSystem.js
> +    if (Number.isInteger(now) === false) {
actually just realized there is a `isNaN` first, so maybe not necessary.

2020-04-14 13:47 UTC, brodrigu commented on modules/sharedIdSystem.js
> +    if (Number.isInteger(now) === false) {
actually, `isNaN('1')` is `false` and `Number.isInteger('1')` is also false, so though I think this more or less safe, still better to clear assumptions first.

2020-04-14 13:47 UTC, brodrigu commented on modules/sharedIdSystem.js
> +    for (; len > 0; len--) {
do we want to error out if `len` is not a number? or is returning an empty string fine?

2020-04-14 13:47 UTC, brodrigu commented on modules/sharedIdSystem.md
> +                name: 'sharedId',
```suggestion
                name: 'sharedid',
```

2020-04-14 13:47 UTC, brodrigu commented on modules/sharedIdSystem.md
> +| storage.name | Required | String | The name of the cookie or html5 local storage where the user ID will be stored. | `"sharedId"` |
```suggestion
| storage.name | Required | String | The name of the cookie or html5 local storage where the user ID will be stored. | `"sharedid"` |
```

2020-04-14 13:47 UTC, brodrigu commented on modules/userId/eids.js
> +    source: 'rubiconproject.com',
```suggestion
    source: 'sharedid.org',
```
Need to confirm with Garrett, but I believe we don't want rubicon as the source.

2020-04-14 13:47 UTC, brodrigu commented on modules/userId/eids.md
> +        source: 'rubiconproject.com',
```suggestion
        source: 'sharedid.org',
```
again, pending confirmation with Garrett

2020-04-14 13:47 UTC, brodrigu commented on modules/userId/userId.md
> +                 name: 'sharedId',
```suggestion
                 name: 'sharedid',
```

2020-04-14 13:47 UTC, brodrigu commented on modules/userId/userId.md
> +                name: 'sharedId',
```suggestion
                name: 'sharedid',
```

2020-04-14 13:47 UTC, brodrigu commented on test/spec/modules/eids_spec.js
> +      source: 'rubiconproject.com',
```suggestion
      source: 'sharedid.org',
```

2020-04-14 13:47 UTC, brodrigu commented on test/spec/modules/userId_spec.js
> +            storage: { name: 'sharedId', type: 'cookie' }
```suggestion
            storage: { name: 'sharedid', type: 'cookie' }
```

2020-04-14 13:47 UTC, brodrigu commented on test/spec/modules/userId_spec.js
> +      localStorage.setItem('sharedId', JSON.stringify({'sharedId': 'test_sharedId'}));
I'm not 100% sure where in this line (and elsewhere in this file) `sharedId` would need to be changed to `sharedid`

2020-04-14 16:36 UTC, jdwieland8282 commented
Docs PR: https://github.com/prebid/prebid.github.io/pull/1923

2020-04-14 19:34 UTC, brodrigu commented on modules/sharedIdSystem.js
> +   * @param {string} the current pseudorandom number
```suggestion
   * @param {string} the current pseudorandom number generator
```

2020-04-15 18:09 UTC, yava-ua commented on modules/sharedIdSystem.js
> +  sharedIdGenerator: function () {
this and below methods do not seem to be related to the submodule. It seems safe to extract them out of the module and just reuse it here. Even if we want to leave factory for submodule use, other methods may be still regular functions

2020-04-23 18:36 UTC, SKOCHERI commented
There has been changes with the sharedId generation hence closing this pull request

2020-04-23 18:36 UTC, closed without merging